spring.application.name: sigure
spring.jackson.serialization:
  write_dates_as_timestamps: false
  indent_output: true

#logging:
#  file: /usr/local/var/log/tomcat/${spring.application.name}/${spring.application.name}.log

management:
  context-path: /monitor
  info.git.mode: full

# custom
tomcat.ajp:
  port: 8009
  enabled: true
